package:
  name: tipp
  version: "1.1.0"

source:
  git_url: https://github.com/Wenfei-Xian/TIPP.git
  git_tag: main  # Use a specific release tag if necessary

build:
  number: 0
  #script: bash ./build.sh

requirements:
  build:
    - {{ compiler('cxx') }}
    - python=3.7
    - make
    - git
    #- bioconductor-biostrings=2.68.1  # from bioconda
    #- flye  # from bioconda
    #- graphaligner=1.0.17  # from bioconda
    #- mcl=22.282  # from bioconda
    #- minimap2=2.26  # from bioconda
    #- spoa=4.1.4  # from bioconda
    #- trf=4.09.1  # from bioconda
    #- r-pheatmap=1.0.12  # from bioconda
    #- r-igraph=1.5.1  # from conda-forge
    #- r-stringdist=0.9.10  # from conda-forge
    #- r-ggplot2=3.4.4  # from conda-forge
    #- kmc=3.2.4
    - zlib=1.2.13
    - bzip2=1.0.8
    #- tiara  # from pypi (requires pip install)
  run:
    - python=3.7
    - tiara
    - graphaligner=1.0.17
    - flye
    - minimap2=2.26
    - spoa=4.1.4
    - mcl=22.282
    - r-pheatmap=1.0.12
    - r-igraph=1.5.1
    - bioconductor-biostrings=2.68.1
    - r-stringdist=0.9.10
    - r-ggplot2=3.4.4
    - trf=4.09.1
    #- kmc

about:
  home: https://github.com/Wenfei-Xian/TIPP
  license: MIT
  summary: "TIPP: A User-Friendly Tool for De Novo Assembly of Organellar Genomes with HiFi Data"
