package:
  name: tipp
  version: "1.1.0"

source:
  git_url: https://github.com/Wenfei-Xian/TIPP.git
  git_tag: main

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # For compiling C++ code
    - python=3.7
  run:
    - python=3.7
    - tiara
    - graphaligner=1.0.17
    - flye
    - minimap2=2.26
    - spoa=4.1.4
    - mcl=22.282
    - r-pheatmap=1.0.12
    - r-igraph=1.5.1
    - bioconductor-biostrings=2.68.1
    - r-stringdist=0.9.10
    - r-ggplot2=3.4.4
    - trf=4.09.1

about:
  home: https://github.com/Wenfei-Xian/TIPP
  license: MIT
  summary: "TIPP: A User-Friendly Tool for De Novo Assembly of Organellar Genomes with HiFi Data"
