package:
  name: genera
  version: "1.4.2"

source:
  git_url: https://github.com/josuebarrera/GenEra.git
  git_tag: v1.4.2
  sha256: d56c5f7430a33bf781a42b325c0cd813e862b06e14d486c411ba5909251ef206

build:
  number: 0

requirements:
  host:
    - python=3.7.12
  run:
    - python=3.7.12
    - diamond=2.1.10
    - mmseqs2=14.7e284
    - foldseek=3.915ef7d
    - scipy=1.7.3
    - r-seqinr=4.2_16
    - r-optparse=1.7.3
    - r-bio3d=2.4_3
    - r-tidyverse=1.3.2
    - r-phytools=0.6_99
    - orthofinder=2.5.5
    - ncbitax2lin=2.3.2

about:
  home: https://github.com/josuebarrera/GenEra.git
  license: GPL-3.0
  summary: "Uncovering gene-family founder events during major evolutionary transitions in animals, plants and fungi using GenEra"
